### ISSUE TITLE
Error: "Unsupported target type found." when running rtcontrol with -V flag

### ISSUE THREAD

**Issue by stereolink** [pyroscope/pyrocore#13]
When running an `rtcontrol` command with `-V` to have it display in an rtorrent view, the `view_filter` method is not found. I'm using rtorrent 0.9.6 and I know that this version has slightly changed the names of some commands. In `rtorrent/src/command_ui.cc` I can see that the `view_filter` command has been renamed `view.filter` - though I'm not sure what needs to be changed in pyrocore. Below is a traceback for the command `rtcontrol -V tagged=`
 
```
Traceback (most recent call last):
  File "/usr/bin/rtcontrol", line 9, in <module>
    load_entry_point('pyrocore==0.4.2', 'console_scripts', 'rtcontrol')()
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/rtcontrol.py", line 619, in run
    RtorrentControl().run()
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/base.py", line 232, in run
    self.mainloop()
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/rtcontrol.py", line 560, in mainloop
    self.show_in_view(view, matches)
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/rtcontrol.py", line 435, in show_in_view
    config.engine.show(matches, targetname)
  File "/usr/lib/python2.7/site-packages/pyrocore/torrent/rtorrent.py", line 671, in show
    proxy.view_filter(view, "false=")
  File "/usr/lib/python2.7/site-packages/pyrocore/util/xmlrpc.py", line 111, in __call__
    return xmlrpclib.loads(xmlresp)[0][0]
  File "/usr/lib/python2.7/xmlrpclib.py", line 1143, in loads
    return u.close(), u.getmethodname()
  File "/usr/lib/python2.7/xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault -506: "Method 'view_filter' not defined">
```

**Comment by stereolink** [comment]
The `pyroadmin --create-config` command did not add a rule of `view_filter = view.filter` to `config.ini`.  After adding this, I still get another error complaining about `Unsupported target type found.`

```
Traceback (most recent call last):
  File "/usr/bin/rtcontrol", line 9, in <module>
    load_entry_point('pyrocore==0.4.2', 'console_scripts', 'rtcontrol')()
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/rtcontrol.py", line 619, in run
    RtorrentControl().run()
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/base.py", line 232, in run
    self.mainloop()
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/rtcontrol.py", line 560, in mainloop
    self.show_in_view(view, matches)
  File "/usr/lib/python2.7/site-packages/pyrocore/scripts/rtcontrol.py", line 435, in show_in_view
    config.engine.show(matches, targetname)
  File "/usr/lib/python2.7/site-packages/pyrocore/torrent/rtorrent.py", line 671, in show
    proxy.view_filter(view, "false=")
  File "/usr/lib/python2.7/site-packages/pyrocore/util/xmlrpc.py", line 111, in __call__
    return xmlrpclib.loads(xmlresp)[0][0]
  File "/usr/lib/python2.7/xmlrpclib.py", line 1143, in loads
    return u.close(), u.getmethodname()
  File "/usr/lib/python2.7/xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault -501: 'Unsupported target type found.'
```

**Comment by pyroscope** [comment]
Start rT with the -D switch in the meantime. And/or make sure you did NOT copy the [XMLRPC_0_8_7] section to your config.ini, else the defaults are shadowed (which contain a proper mapping).

**Comment by stereolink** [comment]
Thanks for getting back to me so quickly. Removing the `view_filter = view.filter` rule I added to config.ini and running with rtorrent with -D flag does work - thanks for the solution.
