### ISSUE TITLE
Problem with config when install from HEAD

### ISSUE THREAD

**Issue by mafrosis** [pyroscope/pyrocore#23]
Create a venv and install:

    mkdir /tmp/pyrocore && cd /tmp/pyrocore
    virtualenv --python python2.7 . && source bin/activate
    pip install git+git://github.com/pyroscope/pyrocore@master

For example, run `pyroadmin --create-config` (same error occurs when I use pyrocore via python CLI).

    > pyroadmin --create-config
    INFO     Total time: 0.001 seconds.
    Traceback (most recent call last):
      File "/tmp/pyrocore/bin/pyroadmin", line 9, in <module>
        load_entry_point('pyrocore==0.4.3.dev20160626', 'console_scripts', 'pyroadmin')()
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/scripts/pyroadmin.py", line 187, in run
        AdminTool().run()
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/scripts/base.py", line 233, in run
        self.get_options()
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/scripts/base.py", line 326, in get_options
        load_config.ConfigLoader(self.options.config_dir).load(self.OPTIONAL_CFG_FILES + self.options.config_file)
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/util/load_config.py", line 223, in load
        self._set_defaults(namespace, optional_cfg_files)
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/util/load_config.py", line 176, in _set_defaults
        defaults = pymagic.resource_string("pyrocore", "data/config/" + cfg_file) #@UndefinedVariable
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1184, in resource_string
        self, resource_name
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1457, in get_resource_string
        return self._get(self._fn(self.module_path, resource_name))
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1580, in _get
        with open(path, 'rb') as stream:
    IOError: [Errno 2] No such file or directory: '/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/data/config/config.ini'

**Comment by pyroscope** [comment]
https://pyrocore.readthedocs.io/en/latest/installation.html#installing-from-source

**Comment by mafrosis** [comment]
I'm not part of "generation youtube" so I have read your docs 😄 , and I've also read the source code. It's not ok to install a python project via a bash script. This is what pip is for.

IMO it's a bug that these two sets of commands produce different results.

Install source into venv (this works):

    cd /tmp
    git clone git@github.com:pyroscope/pyrocore.git
    cd pyrocore
    virtualenv --python python2.7 . && source bin/activate
    pip install -e .
    pyroadmin --dump-config

And install directly from git into venv (this produces the error above):

    mkdir /tmp/pyrocore && cd /tmp/pyrocore
    virtualenv --python python2.7 . && source bin/activate
    pip install git+git://github.com/pyroscope/pyrocore@master
    pyroadmin --dump-config

**Comment by pyroscope** [comment]
Time to learn about using #egg= on direct URLs,

**Comment by mafrosis** [comment]
Yeah my bad on that one. Less snark would be nice though.. It saddens me that open source has to be this way. Good luck with your project.

**Comment by pyroscope** [comment]
“It's not ok to install a python project via a bash script.”

Gimme a break. You started the downhill slope. The script is there for a reason — to reduce my support costs due to user error.

**Comment by mafrosis** [comment]
I stand by that point.

Closing my ticket with a link which says "run this bash script" is not cool. I apologise for wasting your time by needing support, but today you lost a potential contributor.
