### ISSUE TITLE
mktor "UnicodeDecodeError" - Can't generate torrents

### ISSUE THREAD

**Issue by 01100001** [pyroscope/pyrocore#49]
While generating torrents using this command:

    mktor -pv -o ../"file name.txt.torrent" "file name.txt" trackeralias

I get errors like this:

```
DEBUG    Options: comment=None, config_dir=None, config_file=[], cron=False, cross_seed=None, debug=False, defines=[], exclude=[], hashed=False, no_cross_seed=False, no_date=False, output_filename='../file name.txt.torrent', private=True, quiet=False, root_name=None, set=[], verbose=True
DEBUG    Loading '/home/loki/.pyroscope/config.ini'...
DEBUG    Loading '/home/loki/.pyroscope/config.py'...
INFO     Creating '../file name.txt.torrent' for data in 'file name.txt'...
DEBUG    Hashing 'file name.txt', size 487508104...
INFO     Total time: 0.704 seconds.
Traceback (most recent call last):
  File "/home/loki/bin/mktor", line 11, in <module>
    load_entry_point('pyrocore', 'console_scripts', 'mktor')()
  File "/home/loki/.local/pyroscope/src/pyrocore/scripts/mktor.py", line 180, in run
    MetafileCreator().run()
  File "/home/loki/.local/pyroscope/src/pyrocore/scripts/base.py", line 240, in run
    self.mainloop()
  File "/home/loki/.local/pyroscope/src/pyrocore/scripts/mktor.py", line 156, in mainloop
    comment=self.options.comment, created_by="PyroScope %s" % self.version, callback=callback
  File "/home/loki/.local/pyroscope/src/pyrocore/util/metafile.py", line 639, in create
    meta, totalhashed = self._make_meta(tracker_url, root_name, private, progress)
  File "/home/loki/.local/pyroscope/src/pyrocore/util/metafile.py", line 570, in _make_meta
    info, totalhashed = self._make_info(piece_size, progress, self.walk() if self._fifo else sorted(self.walk()))
  File "/home/loki/.local/pyroscope/src/pyrocore/util/metafile.py", line 531, in _make_info
    "pieces": "".join(pieces),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 1: ordinal not in range(128)
```

I am not sure what's wrong. rTorrent seems to run just fine and `rtcontrol` works as well. Just not `mktor` AFAIK. Is there something I can do about this?

***

My server runs:

- Ubuntu 16.04 64-bit LTS
- Python 2.7.12
- rTorrent PS-1.0-58-g55b0ee9 0.9.6/0.13.6 (`~/.local/` shows rTorrent 0.9.6-PS-1.1-dev; installed via build.sh)
- `echo $LANG` shows `en_US.UTF-8`
- System software is up-to-date

***PS**: I was able to create the torrent just fine with Transmission.*

**Comment by pyroscope** [comment]
Thanks for the report.

**Comment by 01100001** [comment]
Thank you for the quick fix!
