### ISSUE TITLE
Missing dependency prompt_toolkit

### ISSUE THREAD

**Issue by akiroz** [pyroscope/pyrocore#57]
**Description:**

Error running `rtxmlrpc`: `ImportError: No module named prompt_toolkit`.

**How to Reproduce:**

```
$ mkdir -p ~/bin ~/.local
$ git clone "https://github.com/pyroscope/pyrocore.git" ~/.local/pyroscope
$ bash ~/.local/pyroscope/update-to-head.sh `which python`
$ rtxmlrpc
```
System: NixOS 17.03

**Working Solution:**

Patch `~/.local/pyroscope/bootstrap.sh`, add `pip_install_opt -U "prompt_toolkit>=1.0.15"` after line 61.

**Comment by pyroscope** [comment]
This is optional, install "pyrocore[repl]".

**Comment by akiroz** [comment]
But wouldn't it be better if the CLI tools worked out-of-the-box after following the installation guide?

**Comment by PyR8zdl** [comment]
Have the same issue, added the Patch as OP provided and now I get...

`rtxmlrpc
Traceback (most recent call last):
  File "/home/pyr8zdl/bin/rtxmlrpc", line 11, in <module>
    load_entry_point('pyrocore', 'console_scripts', 'rtxmlrpc')()
  File "/home/pyr8zdl/.local/pyroscope/src/pyrocore/scripts/rtxmlrpc.py", line 384, in run
    RtorrentXmlRpc().run()
  File "/home/pyr8zdl/.local/pyroscope/src/pyrocore/scripts/base.py", line 267, in run
    self.mainloop()
  File "/home/pyr8zdl/.local/pyroscope/src/pyrocore/scripts/rtxmlrpc.py", line 360, in mainloop
    return self.do_repl()
  File "/home/pyr8zdl/.local/pyroscope/src/pyrocore/scripts/rtxmlrpc.py", line 184, in do_repl
    from prompt_toolkit.contrib.completers import WordCompleter
ImportError: cannot import name WordCompleter`

**Comment by PyR8zdl** [comment]
never mind changed...
 `pip_install_opt -U "prompt_toolkit>=1.0.15"`

to...
`pip_install_opt -U "prompt-toolkit>=1.0.14,<2"`

and it works fine now.
