### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 58-66: ordinal not in range(128)

### ISSUE THREAD

**Issue by MangaValk** [pyroscope/pyrocore#80]
i have set up this scrip https://pyrocore.readthedocs.io/en/latest/custom.html#only-start-items-that-you-have-disk-space-for but keep getting this error,

```2018-12-11 21:49:20 ERROR    Job "QueueManager.run (trigger: cron[second='*/5'], next run at: 2018-12-11 21:49:25)" r
aised an exception [apscheduler.scheduler]
Traceback (most recent call last):
  File "/home/mangavalk/.local/pyroscope/local/lib/python2.7/site-packages/apscheduler/scheduler.py", line 510, in _r
un_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/torrent/queue.py", line 149, in run
    self._start(items)
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/torrent/queue.py", line 71, in _start
    startable = [i for i in items if self.config.startable.match(i)]
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/util/matching.py", line 128, in match
    return all(i.match(item) for i in self)
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/util/matching.py", line 128, in <genexpr>
    return all(i.match(item) for i in self)
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/util/matching.py", line 128, in match
    return all(i.match(item) for i in self)
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/util/matching.py", line 128, in <genexpr>
    return all(i.match(item) for i in self)
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/util/matching.py", line 432, in match
    val = getattr(item, self._name) or False
  File "/home/mangavalk/.local/pyroscope/src/pyrocore/torrent/engine.py", line 251, in __get__
    return self.valtype(self._accessor(obj) if self._accessor else obj._fields[self.name])
  File "/home/mangavalk/.pyroscope/config.py", line 25, in has_room
    stats = os.statvfs(pathname)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 58-66: ordinal not in range(128)```

**Comment by pyroscope** [comment]
Try to change `import os` to `from pyrocore.util import os`.

There might be several of those imports, change each.
