### ISSUE TITLE
Debian Buster, pyroscope can't start

### ISSUE THREAD

**Issue by omgiafs** [pyroscope/pyrocore#88]
After upgrading from Stretch to Buster rtorrent (rtorrent-ps ) can't start.
```
rtorrent@nas:[~]:$uname -a
Linux nas 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

rtorrent@nas:[~]:$cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

```
rtorrent@nas:[~/rtorrent]:$/home/rtorrent/rtorrent/start
rtorrent: Failed to parse command line option: Error in option file: /home/rtorrent/rtorrent/rtorrent.rc:39: Bad return code.
```
String 39 of `/home/rtorrent/rtorrent/rtorrent.rc`:
```
execute.throw = (cat,(pyro.bin_dir),pyroadmin),-q,--create-import,cat,(cfg.basedir),"rtorrent.d/*.rc")
```

```
rtorrent@nas:[~]:$cat /tmp/rtorrent-bootstrap-4835.log

---
/home/rtorrent/bin/pyroadmin -q --create-import /home/rtorrent/rtorrent/rtorrent.d/*.rc
---
Traceback (most recent call last):
  File "/home/rtorrent/bin/pyroadmin", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/rtorrent/.local/pyroscope/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/rtorrent/.local/pyroscope/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

--- Error ---

```
Also pyroscope cannot be upgraded from git:
```
rtorrent@nas:[~]:$.local/pyroscope/update-to-head.sh
~~~ On errors, paste EVERYTHING below ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Installing into /home/rtorrent/.local/pyroscope...
Using Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]
Updating your installation...
Already up to date.
md5sum: .local/pyroscope/update-to-head.sh: No such file or directory
.local/pyroscope/update-to-head.sh: line 46: test: 848640d059c54ed94f3dd659ce8e1681: unary operator expected
Traceback (most recent call last):
  File "./bin/pip", line 7, in <module>
    from pip import main
  File "/home/rtorrent/.local/pyroscope/local/lib/python2.7/site-packages/pip/__init__.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by pyroscope** [comment]
For the 2nd, just remove + reinstall the venv. You cannot change the host Python without breaking venvs.

**Comment by pyroscope** [comment]
No more feedback, closing.
